version: '3.6'

services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # So that Traefik/Caddy can listen to the Docker events
      - caddy_data:/data

  web:
    build: .
    image: youtube-web-downloader
    ports:
     - "2300:2300"
    command: bundle exec foreman start web
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: "postgresql://youtube:$POSTGRES_PASSWORD@postgres/youtube"
      SERVE_STATIC_ASSETS: "true"
    depends_on:
      - redis
      - postgres
    labels:
      caddy: http://:80
      caddy.reverse_proxy: web:2300

  sidekiq:
    image: youtube-web-downloader
    command: bundle exec foreman start sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: "postgresql://youtube:$POSTGRES_PASSWORD@postgres/youtube"
    depends_on:
      - web
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: youtube
      POSTGRES_DB: youtube
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
  caddy_data:
