version: '3.6'

services:
  web:
    build: .
    image: youtube-web-downloader
    ports:
     - "2300:2300"
    command: bundle exec foreman start web
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: "postgresql://youtube:$POSTGRES_PASSWORD@postgres/youtube"
      SERVE_STATIC_ASSETS: "true"
    depends_on:
      - redis
      - postgres

  sidekiq:
    image: youtube-web-downloader
    command: bundle exec foreman start sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: "postgresql://youtube:$POSTGRES_PASSWORD@postgres/youtube"
    depends_on:
      - web
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: youtube
      POSTGRES_DB: youtube
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
